FROM node as build
WORKDIR /app
COPY package.json .
RUN npm config set legacy-peer-deps true
RUN npm install
COPY . .
CMD npm run build

FROM nginx 
COPY --from=build /app/build /usr/share/nginx/html
